### ISSUE TITLE
Consistent capitalization of transform operations 

### ISSUE THREAD

**Issue by HaukeBartsch** [ABCD-STUDY/DEAP#11]
Can we make the transformations all with an initial capital letter? This would also include the 'reset' button.

<img width="288" alt="image" src="https://user-images.githubusercontent.com/603956/46703735-c4cfda80-cbdc-11e8-8594-33fb91e9d279.png">

**Comment by Mosqidiot** [comment]
1. Reset buttons for transformations has been replaced.  By clicking transformations button twice,  transformation will be toggled off.  
2. Capitalization has been applied to all the transformation buttons.
