### ISSUE TITLE
Frozen browser on renaming variables in Scores

### ISSUE THREAD

**Issue by HaukeBartsch** [ABCD-STUDY/DEAP#12]
It seems to depend on the order in which a variable is renamed in the Scores application (first in the next/program, afterwards in the input text field) but the browser (Safari) was freezing up forever and did not do any redraws anymore.

Hope we can replicate this sufficiently...

**Comment by Mosqidiot** [comment]
Cannot reproduce the error.

**Comment by HaukeBartsch** [comment]
I was also not able to reproduce this problem again.
