### ISSUE TITLE
Analyze - Empty first graph

### ISSUE THREAD

**Issue by seanhatton** [ABCD-STUDY/DEAP#13]
I tried this model on my Ubuntu 16.04 machine, Chromium - first graph has points but looks empty, all other results.

![screenshot from 2018-10-11 14-21-17](https://user-images.githubusercontent.com/41756439/46834893-86aff380-cd61-11e8-9d01-edbc7a65fae6.png)

**Comment by Mosqidiot** [comment]
Can you also post a screenshot for the definition of your subset "Recommended T1w"?

**Comment by Mosqidiot** [comment]
This problem can not be reproduced.
