### ISSUE TITLE
Scores created by other users show in the Scores application but cannot be opened

### ISSUE THREAD

**Issue by HaukeBartsch** [ABCD-STUDY/DEAP#17]
Scores created by other users show in the Scores application but cannot be opened. 

We should not show scores created by other users if they cannot be opened by the current user.

**Comment by HaukeBartsch** [comment]
This should be fixed now on abcd-deap.ucsd.edu. getScores.php is only showing admin and the currently logged in user's scores. I also changed "admin" to "public" to indicate that these scores are for everyone.

Someone needs to check if this is ok now.

**Comment by Mosqidiot** [comment]
Just checked with my account. It is Ok.
