### ISSUE TITLE
Data transformations in analyse not working

### ISSUE THREAD

**Issue by cpalmer14** [ABCD-STUDY/DEAP#21]
Hi, I'm using DEAP internally through ABCD reports on Google Chrome.  Transforming either the dependent or independent variables crashes the analysis.  This happens no matter which transformation is used.  Below is an example using the log transformation.

![deapissue1](https://user-images.githubusercontent.com/44177108/46974097-e9620180-d077-11e8-917d-99d3f265a9f1.png)
![deapissue2](https://user-images.githubusercontent.com/44177108/46974326-95a3e800-d078-11e8-84eb-56c04807fd9d.png)

**Comment by Mosqidiot** [comment]
It is a bug caused by this morning updates. It has been solved now.

**Comment by Mosqidiot** [comment]
I had the same issue on Chrome, Mac. It seems like log() function is slightly off. 
![image](https://user-images.githubusercontent.com/14843948/46979455-8deb4000-d086-11e8-8304-180407972ab9.png)

**Comment by HaukeBartsch** [comment]
We should filter the array before we apply the log function. That would make it easier for people to use this function - instead of using subsetting to filter out the participants that break the conversion.

**Comment by cpalmer14** [comment]
This worked for me just now.

**Comment by HaukeBartsch** [comment]
Thanks for letting us know!

**Comment by tashawade** [comment]
I seem to be having the same issue on deaptest on Chrome, but on newly created variables through Extend. Is it possible that having created the variable somehow makes it not work with this fix?

<img width="872" alt="deap3" src="https://user-images.githubusercontent.com/44237822/47451320-4c405080-d77c-11e8-827f-a4ea2fa39973.PNG">
