### ISSUE TITLE
Screentime summary score has many missing values

### ISSUE THREAD

**Issue by tashawade** [ABCD-STUDY/DEAP#23]
Hi, I'm using deaptest on a chrome on a PC. When I try to run screen time variables, I get this error:
<img width="882" alt="deaperror" src="https://user-images.githubusercontent.com/44237822/47098280-c7878c80-d1e7-11e8-808f-716d57056c38.PNG">

Thanks in advance!

**Comment by HaukeBartsch** [comment]
We are looking into this issue. Seems to be caused by a missing alias. The name for this variable is actually screentime_ss_weekday. We have updated this in our transformation code. This change should be active in the next couple of hours - we will ask NDA to re-build using our sources.

**Comment by tashawade** [comment]
Thanks for getting that fixed! I have a new question on this issue for the screen time variables. The n is now only around 1,300. About a month ago it was closer to 2900. Any idea why that might be?

**Comment by HaukeBartsch** [comment]
For stq_y_ss_weekday there are currently about 3,000 missing values, so there should be about 1,500 values you can use in an analysis. I don't know why it would have been 2,900. Do you have some documentation for those?
As you know the 1.1 data release is not yet finalized/announced. It is therefore possible that the data will change.

**Comment by tashawade** [comment]
I did these analyses before I realized that I could save the output, therefore I copied the page into a microsoft word doc. While not perfect, here's some of that:

Model Formula
tfmri_sst_all_correct.stop.vs.correct.go_beta_cort.desikan_caudalanteriorcingulate.lh ~ stq_y_ss_weekday + cbcl_scr_syn_external_t + tlfb_alc_sip + tlfb_mj_puff + pmq_y_ss_mean + race.ethnicity + sex + high.educ + married + interview_age + household.income
Random: ~(1|abcd_site/rel_family_id)


  | level | Overall
-- | -- | --
 
n |   | 2900
tfmri_sst_all_correct.stop.vs.correct.go_beta_cort.desikan_caudalanteriorcingulate.lh   (mean (sd)) |   | 35.58   (1912.47)
stq_y_ss_weekday (mean (sd)) |   | 3.20   (2.78)


 
--
  | Effect   Size
 
N | 2900
R-squared | -0.04869
ΔR-squared | -0.05209   (-5.21%)
 
Sorry it doesn't look cleaner!

**Comment by HaukeBartsch** [comment]
Ok, we found the issue. The variable type was changed on our end from Number to Integer which prevents values with decimal points from being exported to NDA. We will fix this issue on our end and re-upload the data to NDA. Thanks for your patients!

**Comment by tashawade** [comment]
Thanks, Hauke! Any update on when this fix might happen? I've tried re-running the analyses, with the same N coming up due to the missing values

**Comment by HaukeBartsch** [comment]
Actually yes. I am creating the new nda17.Rds file right now and wanted to ask you to check them on deaptest tomorrow. Hopefully all the values are now there.

**Comment by tashawade** [comment]
Great, thank you! I'll check it out tomorrow and report back

**Comment by HaukeBartsch** [comment]
Seems to be fixed:

<img width="1128" alt="image" src="https://user-images.githubusercontent.com/603956/47510400-ee1f7600-d82c-11e8-9f38-55d572ca3cfe.png">

**Comment by tashawade** [comment]
It is for me as well. THANK YOU!
