### ISSUE TITLE
No summary scores for RAVLT

### ISSUE THREAD

**Issue by cpalmer14** [ABCD-STUDY/DEAP#24]
There are no summary scores for the Rey Auditory-Verbal Learning Task.

Is there a way to produce your own summary scores in DEAP? E.g. if you wanted to average over or sum a particular selection of questions in a questionnaire.

**Comment by HaukeBartsch** [comment]
There is a sum scores that is calculated in the "Extend" application on DEAP. We will check that application tomorrow morning after the nightly update. Here is the code that calculates the sum of the 5 RAVLT scores (see pea_ravlt_sum_trials in Extend):

### Sum of 5 learning trials for the RAVLT
Why should the reader be interested in this new item? Describe your rationale to provide it and explain your sources. Start the computation of the new item by listing required existing items, for example age here:
```
var promises = use(["pea_ravlt_sd_trial_i_tc", "pea_ravlt_sd_trial_ii_tc", "pea_ravlt_sd_trial_iii_tc", "pea_ravlt_sd_trial_iv_tc", "pea_ravlt_sd_trial_v_tc"]);
```
Here we can do the computation. We want to check if all the variables exist before computing the sum of the 5 arguments. The initial plus sign in the computation is used to convert the text column <code>a</code> to a number.
```
function calc(a, b, c, d, e) {
    if (isNaN(a) || isNaN(b) || isNaN(c) || isNaN(d) || isNaN(e)) {
        return '';
    }
    return +a+b+c+d+e;
}
```

Add the calculation of the new measure in another section delimited by three tick marks:
```
Promise.all(promises).then( function() {
  var data = new DataFrame(allMeasures);
  data = data.map(row => row.set("pea_ravlt_sum_trials", +calc(row.get("pea_ravlt_sd_trial_i_tc"), row.get("pea_ravlt_sd_trial_ii_tc"), row.get("pea_ravlt_sd_trial_iii_tc"), row.get("pea_ravlt_sd_trial_iv_tc"), row.get("pea_ravlt_sd_trial_v_tc"))  ));
  update(data, 'pea_ravlt_sum_trials');
});
```

**Comment by cpalmer14** [comment]
Ah sorry forgot about extend - thanks Hauke!  I just tried using one of the summary scores in Analyse though and it says that variable doesn't exist.

![tmp](https://user-images.githubusercontent.com/44177108/47167521-94aaca80-d2b3-11e8-8b77-821151e0506e.PNG)

**Comment by Mosqidiot** [comment]
The histogram view of user defined scores is a functionality that is missing now and we are working on fixing it. However, the variable actually exists in the database and you can submit the model to see the result.

**Comment by wkthompson123** [comment]
I think it may be fixed now?

**Comment by HaukeBartsch** [comment]
I can still see two problems:

<img width="1259" alt="image" src="https://user-images.githubusercontent.com/603956/47248549-03754a00-d3c0-11e8-8d04-625b2616d4f1.png">

**Comment by Mosqidiot** [comment]
The issue has been partially fixed that you can run the model with the score but not a histogram view in the floating window. The error posted by Hauke is fixed now. I am still working on the histogram view.

**Comment by Mosqidiot** [comment]
Finally, histogram view for score has been implemented on abcd-deap.  
![image](https://user-images.githubusercontent.com/14843948/47252302-5fa79080-d3f7-11e8-892a-70c1f4d821af.png)

**Comment by HaukeBartsch** [comment]
Still not working on deaptest. 
<img width="1333" alt="image" src="https://user-images.githubusercontent.com/603956/47260344-a6849d00-d46e-11e8-9565-e5e3c292fb15.png">

**Comment by HaukeBartsch** [comment]
Works now, thanks!
