### ISSUE TITLE
Funky login page after entering wrong credentials 

### ISSUE THREAD

**Issue by vvvvvickyz** [ABCD-STUDY/DEAP#25]
After entering the wrong credentials, the login page showed an error message on the top of the page, and the log in boxes were a little distorted (the height of the username and password box got smaller). 

<img width="1221" alt="screen shot 2018-10-17 at 4 37 30 pm" src="https://user-images.githubusercontent.com/31934995/47122268-f7a44f00-d22a-11e8-8bc0-3dc5659b44f4.png">

**Comment by HaukeBartsch** [comment]
This should be fixed tomorrow. We expect an error message to show if either the password/user name was wrong or if the account on NDA does not have permissions to see ABCD data.

**Comment by Mosqidiot** [comment]
Just tested. This issue is fixed on my end. Close the issue.
