### ISSUE TITLE
Select Subset of Session not working

### ISSUE THREAD

**Issue by tashawade** [ABCD-STUDY/DEAP#26]
Using deaptest on a PC. The select subset of sessions gives this error:

![deap](https://user-images.githubusercontent.com/44237822/47162994-ebaba200-d2a9-11e8-86b7-91d513600461.JPG)

I've also tried using other subset selections (e.g., gender) and gotten the same error.

Thanks!

**Comment by wkthompson123** [comment]
Thanks Tasha, we're working on fixing that bug.

**Comment by HaukeBartsch** [comment]
This issue seems to be fixed now. Please give it a try and let us know if it is still not working.

**Comment by tashawade** [comment]
It's working for me as well. Thank you!
