### ISSUE TITLE
sleep disturbance variables are empty

### ISSUE THREAD

**Issue by lkmcevoy** [ABCD-STUDY/DEAP#27]
All the sleep disturbance variables (ag sleepdisturb1_p) are empty. Maybe alias issue?

**Comment by lkmcevoy** [comment]
May be broader problem. Variables in many other mental and physical health categories are missing too (eg. TBI screen; resiliency, life events - the same variables that were not expanding out in the bug I sent you by email Hauke (life events still not expanding).

**Comment by wkthompson123** [comment]
Hopefully this was fixed with the new build, can you please check again? Thanks Linda!

**Comment by lkmcevoy** [comment]
Yes, it seems to be fixed now.
________________________________
