### ISSUE TITLE
high.edu

### ISSUE THREAD

**Issue by wkthompson123** [ABCD-STUDY/DEAP#30]
When you code the “high.edu” variable in R as numeric, in order to do a correlation for example, the education levels are not currently saved in the correct order which then means the coding is wrong.  For example, “some college” is at the end of the list (you can see this in DEAP) therefore becomes coded as 5 (the highest education level) but it is not the highest education level.  I only noticed because I was expecting a correlation and didn’t see one so had to recode the variable in R to correct it – could lead to some errors.

**Comment by HaukeBartsch** [comment]
Can you let me know how you coded it as numeric? Did you use the Score application or expert mode? Might be easy to show you how to get a proper computation given the current order of levels in the Score application.
  Hauke

**Comment by cpalmer14** [comment]
Hi Hauke I did this with the downloaded data in R.  I just used 'as.numeric' and this scores the variable incorrectly because of the education levels are in the wrong order.  You can see this when you look at the histogram.

![tmp](https://user-images.githubusercontent.com/44177108/47302696-0007db80-d5d7-11e8-9072-7dcbf784a347.PNG)

**Comment by HaukeBartsch** [comment]
Hi Clare, Thanks! Yes, we can change the ordering of the levels on GitHub.com/ABCD-STUDY/analysis-nda17/. That is the location that does the coding for these variables.

**Comment by wkthompson123** [comment]
I think we need to recode the variable as follows:

levels(high.edu) = c("<HS Diploma","HS Diploma/GED","Some College","Bachelors","Post Granduate")

**Comment by wkthompson123** [comment]
FYI, I think "as.numeric" will always put the categories in the order they occur in the data.

**Comment by wkthompson123** [comment]
See this:

https://stackoverflow.com/questions/3418128/how-to-convert-a-factor-to-integer-numeric-without-loss-of-information

**Comment by cpalmer14** [comment]
I've just realised the same is true for household income

**Comment by HaukeBartsch** [comment]
I also fixed that one.

**Comment by HaukeBartsch** [comment]
Hi Clare, can you check tomorrow morning that this is now working for household.income, highest.education, and high.educ?

Thanks!

**Comment by cpalmer14** [comment]
Yep no problem.

On 22 Oct 2018, at 18:58, Hauke Bartsch <notifications@github.com<mailto:notifications@github.com>> wrote:


Hi Clare, can you check tomorrow morning that this is now working for household.income, highest.education, and high.educ?

Thanks!

**Comment by cpalmer14** [comment]
Yes both look good now.
