### ISSUE TITLE
extend variable (age_dichot) not showing up in Analyze

### ISSUE THREAD

**Issue by wkthompson123** [ABCD-STUDY/DEAP#34]
Running NDA DEAP on Chome. 

Tried analysis with age_dichot as independent variable (defined in public "Extend"). It's not showing up in analyze.
<img width="1447" alt="screen shot 2018-10-20 at 6 00 05 pm" src="https://user-images.githubusercontent.com/44100683/47262052-57e8fa00-d492-11e8-9e02-757b1d2a704e.png">

**Comment by Mosqidiot** [comment]
Just fixed. 
![image](https://user-images.githubusercontent.com/14843948/47262170-12c6c700-d496-11e8-9ea2-74469e7883a1.png)

**Comment by HaukeBartsch** [comment]
Works for me as well.
