### ISSUE TITLE
Analysis: duplicate figure caption 4

### ISSUE THREAD

**Issue by HaukeBartsch** [ABCD-STUDY/DEAP#4]
Toggling the "Tutorial Model" option in Analysis on and off several times creates a series of "Fig. 4: Model formula in R format." on the page. The expectation is that there is only a single figure capture if the tutorial mode is active.

Tested on MacOS, Safari browser.

**Comment by Mosqidiot** [comment]
It has been fixed.

**Comment by Mosqidiot** [comment]
It has been fixed by adding a div wrapper for formula class objects, and avoid to have multiple places for inserting the tutorial text
