### ISSUE TITLE
Extend Variables Errors

### ISSUE THREAD

**Issue by tashawade** [ABCD-STUDY/DEAP#48]
On deaptest on Chrome on a PC.

I'm playing around with the Extend portion of DEAP. I'm having trouble creating variables. I fully admit this may be user error. However, variables load but won't actually save. At times, I get a promises error (can't get that to replicate at the moment).
<img width="1900" alt="screenshot1" src="https://user-images.githubusercontent.com/44237822/47389270-33c32e00-d6c9-11e8-86a4-c42f8feacf9f.png">

The variable then still will appear in Analyze, but, unsurprisingly, does not work.
<img width="846" alt="screenshot2" src="https://user-images.githubusercontent.com/44237822/47389307-489fc180-d6c9-11e8-8875-17c7fca68afe.png">

Is it possible to make Extend more user-friendly? Or provide more tips on how to use it in the interface? I've been trying to build off the examples but haven't been able to be successful.

**Comment by cpalmer14** [comment]
I've had a similar problem.  I've tried to create a sum from some items in one of the questionnaires almost directly copying the syntax used for the RAVLT summary scores but it won't work.  It says the variable is unsaved however it does actually appear in Analyse (although it's an empty variable).

![tmp](https://user-images.githubusercontent.com/44177108/47393645-ed73cc00-d6d4-11e8-85bc-dc00c96ef491.PNG)

**Comment by cpalmer14** [comment]
I agree it's not very user friendly and difficult to navigate.

**Comment by cpalmer14** [comment]
The variable now seems to be saved but the histogram doesn't appear in Analyse and the model won't run.

![tmp](https://user-images.githubusercontent.com/44177108/47400013-46049280-d6f0-11e8-8ca2-a7ff92041412.PNG)

**Comment by HaukeBartsch** [comment]
I checked your code for the calculation of the variable (see image and code below). I found that the upps variables are categorial variables (see the table and the Explore application screenshot below) and can therefore not be used in a calculation that simply adds them. This is visible in the first table column showing the result of the computation, all values are 'null' (equals NA). For such a column no histogram information is displayed.

<img width="1639" alt="image" src="https://user-images.githubusercontent.com/603956/47406407-f089af00-d70a-11e8-8b20-d92647f5a18b.png">

```
var promises = use(["upps_15", "upps_19", "upps_22", "upps_24"]);
```
 
```
function calcUPPS(a,b,c,d) {
     if (isNaN(a) || isNaN(b) || isNaN(c) || isNaN(d)) {
         return NaN;
     }
     return +a+b+c+d;
}
```

Add the calculation of the new measure in another section delimited by three tick marks:
```
Promise.all(promises).then( function() {
  var data = new DataFrame(allMeasures);
  data = data.map(row => row.set('upps_drive_sum', calcUPPS( row.get("upps_15"), row.get("upps_19"), row.get("upps_22"), row.get("upps_24")) ));
  update(data, 'upps_drive_sum');
});
```

<img width="602" alt="image" src="https://user-images.githubusercontent.com/603956/47406511-88879880-d70b-11e8-9e08-3461d021a92f.png">

**Comment by HaukeBartsch** [comment]
One of the fixes implemented prevents one issue with the first screen time example. The element name should have only lower case letters. Entering upper case letters is not possible anymore. 
I checked the variables in the Explore application and the actual value of the variables is different. Its screentime_1_hours_p and screentime_1_minutes_p. Here is a screenshot:
<img width="627" alt="image" src="https://user-images.githubusercontent.com/603956/47407229-ff726080-d70e-11e8-84d4-3d1165d1a401.png">

I reimplemented the score and got:
<img width="1290" alt="image" src="https://user-images.githubusercontent.com/603956/47407313-58da8f80-d70f-11e8-9a10-8700b201f522.png">

which looks ok. Can you check again? Here is the source code for the score:

```
var promises = use(["screentime_1_hours_p", "screentime_1_minutes_p"]);
```

```
function calcScreentime(a,b) {
    if (isNaN(a) || isNaN(b)) {
        return '';
    }
    return +a+b;
}
```

Add the calculation of the new measure in another section delimited by three tick marks:
```
Promise.all(promises).then( function() {
  var data = new DataFrame(allMeasures);
  data = data.map(row => row.set('parent_st_weekday', +calcScreentime(row.get('screentime_1_hours_p'), row.get('screentime_1_minutes_p')/60)  ));
  update(data, 'parent_st_weekday');
});
```

**Comment by tashawade** [comment]
That worked, thank you!

**Comment by cpalmer14** [comment]
Thanks so much Hauke.  When I was calculating the score yesterday I couldn't see the table of variables next to element name whilst I was editing it.  I've just tried again with a new variable and you still need to save the variable and then refresh the browser in order to see the table and histogram of variables.  Otherwise it seems to be working fine if the calculation is valid!!

**Comment by HaukeBartsch** [comment]
Happy to hear it. Please let me know if there are other scores we can help with.

**Comment by HaukeBartsch** [comment]
'If the calculation is valid', yes that is the curial point. I wonder why you did not see the table yesterday, there must have been something different then. I fixed the issue with the updating of the header line after you save a score. That should work now. You might have to Shift-Reload your browser to see that change as well.
