### ISSUE TITLE
Alcohol spelt wrong in variable names

### ISSUE THREAD

**Issue by cpalmer14** [ABCD-STUDY/DEAP#51]
Alcohol is spelt wrong in some of the variable names which makes searching slightly difficult!

![image](https://user-images.githubusercontent.com/44177108/47462570-8fa8b800-d798-11e8-8cca-a6783ca55374.png)

**Comment by HaukeBartsch** [comment]
LOL, yeah I see. Thanks for reporting that one :-)

We need to fix our variables in REDCap. This will probably be done for the next release (full baseline) next year.

**Comment by HaukeBartsch** [comment]
On DEAP we do have an alias file that was updated with the correct spelling. This change will solve this issue as its reported here. The change should be in effect tomorrow. Please verify.
