### ISSUE TITLE
Appearance of interface error when multiple other independent variables added

### ISSUE THREAD

**Issue by cpalmer14** [ABCD-STUDY/DEAP#52]
Hi I'm using internal DEAP on Chrome.  When I add more than 4 or 5 other variables, at first the first ones I had typed in disappeared and then they started writing below the input box and the submit button shifted.  The model worked fine it's just a bug in the appearance.

![image](https://user-images.githubusercontent.com/44177108/47463664-b4eaf580-d79b-11e8-971a-47016cafb9ad.png)

**Comment by HaukeBartsch** [comment]
I labeled this as an enhancement because we should just make the input box larger. That would allow an easier entering of the other independent variables in several rows.

**Comment by HaukeBartsch** [comment]
Small improvement the "Data display.." is not overlapping with the submit button anymore.

**Comment by cpalmer14** [comment]
I just logged onto DEAP internal on Internet Explorer and the appearance is all wrong... Not sure if this is to do with this same issue?

![image](https://user-images.githubusercontent.com/44177108/47516591-b15a7b80-d83a-11e8-84b2-942b28c05406.png)

**Comment by HaukeBartsch** [comment]
We have an enhancement request that we are working on. Please be patient, should be ok again later today.

**Comment by cpalmer14** [comment]
No worries! Just wanted to flag it in case you hadn't realised!

**Comment by Mosqidiot** [comment]
Should be good  now! Thanks for pointing it out! 
![screen shot 2018-10-25 at 1 46 25 pm](https://user-images.githubusercontent.com/14843948/47529434-a4e71a80-d85c-11e8-82e7-b9ba39addc9a.png)
![screen shot 2018-10-25 at 1 46 26 pm](https://user-images.githubusercontent.com/14843948/47529437-a6184780-d85c-11e8-854a-0683dc65f1aa.png)

**Comment by Mosqidiot** [comment]
Should be good now! Thanks for pointing it out!

**Comment by Mosqidiot** [comment]
![screen shot 2018-10-25 at 1 46 12 pm](https://user-images.githubusercontent.com/14843948/47529543-fe4f4980-d85c-11e8-914b-b3d05fa591e3.png)
![screen shot 2018-10-25 at 1 46 26 pm](https://user-images.githubusercontent.com/14843948/47529548-00b1a380-d85d-11e8-8933-19f32f1acaa5.png)
