### ISSUE TITLE
limit section: nback recommended 

### ISSUE THREAD

**Issue by mdcornej** [ABCD-STUDY/DEAP#53]
the recommended task fMRI - nBack is 
fsqc_qc = pass and 
tfmri_mid_beh_perform_flag = 1 (should it be nback?) and 
tfmri_sst_all_beta_dof > 200 (should it be nback)? 
... you get the idea. 

-Dani.

**Comment by HaukeBartsch** [comment]
Hi Dani, yes we will fix it today. Should be on deaptest tomorrow morning. Thanks for reporting it.

**Comment by HaukeBartsch** [comment]
We are keeping scores from the day before now (Scores and Filter). I had to move the public.json over manually to make it work again. Need to update refresh_deap.sh on NDA.
