### ISSUE TITLE
Link to ABCD Github in Getting Started

### ISSUE THREAD

**Issue by wkthompson123** [ABCD-STUDY/DEAP#55]
Is it possible to do this? And tell people how to report bugs?

**Comment by HaukeBartsch** [comment]
The DEAP project on GitHub is linked on Getting Started. If you follow the RRID in "How to cite DEAP" you will end up on scicrunch and the homepage of DEAP is listed there as the GitHub address. 

Yes, it would be better to put a separate section in there... I will have a look.
