### ISSUE TITLE
less than 2 values error returned for continuous variable nihtbx_fluidcomp_uncorrected

### ISSUE THREAD

**Issue by HaukeBartsch** [ABCD-STUDY/DEAP#6]
Reported by Cindy during DEAP workshop:

"less than 2 values" error returned for variables even after checking distribution; get same error on variables that have been successfully used before.  See screenshot below.

Error provenance:  Dell PC laptop, W10, Edge browser; error reproduced using FireFox.  Using the "Add" function  in the data ontology seems to be what breaks it.  If I type in the name manually, it seems to work ok.

![image](https://user-images.githubusercontent.com/603956/46506825-9bd9cf00-c803-11e8-8e34-877a99bf3489.png)

**Comment by HaukeBartsch** [comment]
This seems to be related to finding the data by the variable names. What seems to happens is that one variable in the model does not have any values. If the system collates the dataset for the analysis all rows are removed and only the first variable appears in the error message (the wrong variable and the wrong message).

**Comment by Mosqidiot** [comment]
Fixed by updating the nda data with release 1.1.
