### ISSUE TITLE
Home page/overall enhancements

### ISSUE THREAD

**Issue by wkthompson123** [ABCD-STUDY/DEAP#61]
The section headers (“plan”, “explore”, etc.) are not intuitive – I had to click on each to figure out what it does. For example, the first thing I wanted to do was look at the data dictionary, and had no idea which link would take me there. The alt text helps, but it would help to change the section headers too, IMHO.

Related to previous, the section headers on the linked pages don’t match those on the home page or the alt text. For example, “Limit”, for which the alt text says “Filter participants”, takes you to a page called “Subsetting ABCD”. This makes it harder to remember what the sections are. Being consistent would make for a smoother experience.

**Comment by HaukeBartsch** [comment]
It is a fine balance between simplicity and accuracy - finding out what names work best for the different tools. Maybe our current names are too simplistic? They are more designed for a non-statistician.
Yes, definitely have to make the names consistent!
