### ISSUE TITLE
When 'censoring' table doesn't update

### ISSUE THREAD

**Issue by cpalmer14** [ABCD-STUDY/DEAP#63]
Using internal DEAP on Chrome. When you censor a variable you can see the histogram change so you know subjects have been removed but none of the values in the table update to reflect this.

![image](https://user-images.githubusercontent.com/44177108/47527018-5afb3600-d856-11e8-8098-f76e7045b37d.png)
![image](https://user-images.githubusercontent.com/44177108/47527041-68182500-d856-11e8-999a-9cae07d14a1b.png)

**Comment by Mosqidiot** [comment]
This issue has been solved!
