### ISSUE TITLE
On small screens the Explore hierarchy plot should initially focus on the domains

### ISSUE THREAD

**Issue by HaukeBartsch** [ABCD-STUDY/DEAP#69]
(from Kenny)
On small screens the domains are only partially visible. The domains should be moved more to the left.

**Comment by wkthompson123** [comment]
Also when you open up Explore, the domains extend out from abcd and disappear off the screen. Maybe this is what you mean?

**Comment by HaukeBartsch** [comment]
Yes, that is what I mean.

**Comment by wkthompson123** [comment]
Maybe when it opens, instead of the new leaves going forward, the new leaves can stay in the center and the roots get pushed backwards.
