### ISSUE TITLE
abcd_site is not in DEAP

### ISSUE THREAD

**Issue by wkthompson123** [ABCD-STUDY/DEAP#70]
See attached. The name or alias must have changed.
<img width="1401" alt="screen shot 2018-10-26 at 12 47 31 pm" src="https://user-images.githubusercontent.com/44100683/47589242-6bc2af00-d91d-11e8-9501-03ffc326fdc2.png">

**Comment by wkthompson123** [comment]
Evidently it is now "site_id_l"? Not sure why now there are 22 sites? This is confusing. 
<img width="678" alt="screen shot 2018-10-26 at 12 49 44 pm" src="https://user-images.githubusercontent.com/44100683/47589321-aaf10000-d91d-11e8-9175-badf7b464009.png">

**Comment by HaukeBartsch** [comment]
This has been fixed on abcd-deap. Please check again tomorrow to see if its fixed on deaptest as well.

**Comment by wkthompson123** [comment]
I just looked on both ABCD DEAP and NDA DEAP, and neither has abcd_site, and there are 22 sites listed for both using site_id_l

**Comment by HaukeBartsch** [comment]
It works now. Please check deaptest tomorrow to verify.

<img width="595" alt="image" src="https://user-images.githubusercontent.com/603956/47592870-fd381e00-d929-11e8-8a70-23ad72a6eaf0.png">

**Comment by wkthompson123** [comment]
OK thanks. Why are there 22 sites though? I thought the baseline data only had 20 sites?

**Comment by wkthompson123** [comment]
I see site_07 doesn't appear. Still, what is site22 and why are there 35 kids there?

**Comment by HaukeBartsch** [comment]
Ok, this is an error in the data. Site 22 does not exist. Let me find out where those participants go. Easy to fix on our end. I will send an email today.

**Comment by HaukeBartsch** [comment]
The reason that one site does not appear is that none of their participants made the cutoff date for the interim release. The site22 code is used to indicate some participants from a discontinued site. 

It is worthwhile to mention here again that site assignment is dependent on the visit. The 35 participants will only be part of site22 for the baseline cohort, not for the followup events as most of them have transferred to another ABCD data collection site.
