### ISSUE TITLE
Additional "censor"-ing occuring with multiple independent variables

### ISSUE THREAD

**Issue by cpalmer14** [ABCD-STUDY/DEAP#77]
Hi When I put a lot of independent variables in a model and some of them are censored, sometimes when I hit the submit button lots of additional "censor" functions are added in.  Also sometimes the analysis crashes because the '+' icons between the variables disappear so they become one long variable.

![image](https://user-images.githubusercontent.com/44177108/47879207-45998500-dddd-11e8-974d-955cf1f44470.png)

**Comment by cpalmer14** [comment]
When I just added in another independent variable after running an analysis all the '+' signs between the variables already in the model disappeared as I mentioned above.

![image](https://user-images.githubusercontent.com/44177108/47879586-35ce7080-ddde-11e8-8d73-478b97955a4d.png)

**Comment by Mosqidiot** [comment]
Hi Clare, 

This bug has been fixed. Please test aground if you still see any issues. Thanks for helping us improve DEAP!
