### ISSUE TITLE
Expired Certificate

### ISSUE THREAD

**Issue by robloughnan** [ABCD-STUDY/DEAP#85]
url has expired certificate which stops some browsers from going onto the page 

<img width="723" alt="image" src="https://user-images.githubusercontent.com/25045134/51068896-d8bf1a00-15d9-11e9-8263-eba280e6bcae.png">

**Comment by HaukeBartsch** [comment]
We will notify the NIMH data archive about this problem. As soon as the US funds their government again they will be able to renew the certificate.

**Comment by HaukeBartsch** [comment]
I noticed this much later, but the certificate is for abcd-deap.ucsd.edu which is our internal version of DEAP. This error has been fixed.
