### ISSUE TITLE
"Undefined column selected" for variable fes_ss_fc_pr

### ISSUE THREAD

**Issue by hannahkim515** [ABCD-STUDY/DEAP#89]
When trying to run analyses with variable fes_ss_fc_pr (Conflict Subscale from the Family Environment Scale, Sum of Youth Report: Prorated Score), DEAP returns an error as follows:

Error in `[.data.frame`(data, , vars_i[1]) : undefined columns selected

<img width="877" alt="gitupload" src="https://user-images.githubusercontent.com/43856094/56968051-6e9e9680-6b30-11e9-8148-db2b94d882a3.PNG">

**Comment by Mosqidiot** [comment]
It seems like fes_ss_fc_pr has been changed to fes_y_ss_fc_pr in release 2. Please use fes_y_ss_fc_pr instead.
