### ISSUE TITLE
iPad issue for Filter prevents setup of new filters

### ISSUE THREAD

**Issue by HaukeBartsch** [ABCD-STUDY/DEAP#92]
With version 2.0 of the NDA18.Rds data the Filter application will not work anymore with an iPad (even with the 256mb version). The page will crash the browser if a filter has been selected.

**Comment by HaukeBartsch** [comment]
This is liked caused by the rendering of many different div elements. I suggest to do a timeout on the pull/draw on low power systems. Even if none of the div elements can be rendered the total number of elements should still be displayed and users should be able to edit/save a filter.

**Comment by Mosqidiot** [comment]
Tested in Beta DEAP. It works fine on my ipad-mini. Recent update on rendering less will solve this issue.

![image](https://user-images.githubusercontent.com/14843948/58292937-404f5800-7d78-11e9-81ff-99790b4bad61.png)
